### ISSUE TITLE
init_entities eats all my memory!

### ISSUE THREAD

**Issue by mikaem** [MiroK/FEliX.jl#2]
Hi

I just tried to `init_entities!(mesh, 1)` for a `mesh = unit_square_mesh(256, 256)` and it segfaults after eating 7GB of memory. Probably room for a more memory-friendly algorithm:-) I can have a closer look, but you @presheaf may have an idea of what's so memory hungry?

**Comment by MiroK** [comment]
Some observation that might be helpful in identifying the cause (note that `init_entities!` has been JIT compiled) before the following is run)

```bash
julia> @time mesh = unit_square_mesh(100, 100);
  0.042356 seconds (443.52 k allocations: 12.495 MB)

julia> @time mesh = unit_square_mesh(100, 100);
  0.051649 seconds (443.52 k allocations: 12.495 MB)

julia> @time init_entities!(mesh, 1);
ERROR: StackOverflowError:
 in typejoin(::Any, ::Type{T}, ::Type{T}, ::Vararg{Type{T},N}) at ./promotion.jl:7 (repeats 19637 times)
 in eltype(::Type{Iterators.Chain{Tuple{Array{Any,1},Array{Any,1},Array{Any,1},Array{Any,1},Array{Any,1},Ar
```

So it seems like an issue with chaining so many iterators.

**Comment by presheaf** [comment]
Yes, I think Miro is right. I was just being lazy with iterators. I think I can reduce mem use by a factor 20 or so by changing 2 lines, let me just verify it and I'll push. :)

**Comment by mikaem** [comment]
Also, when I do `@code_warntype init_entities!(mesh, 1)` I see a lot of undeclared types (Anys). This may also be important for performance.

**Comment by presheaf** [comment]
Commit e468eafb should fix this - init_entities!(mesh, 1) on the 200x200 mesh required 250MB on my machine as opposed to the >8GB it wanted before. As for the types, you're right - I don't entirely understand Julia types yet, so I've avoided type declarations a couple of places where adding them should be easy if you know what you're doing. I will get around to it Soon. :)
